core/src/main/java/com/apighost/model/scenario/HTTPMethod.java, core/src/main/java/com/apighost/model/scenario/ProtocolType.java, core/src/main/java/com/apighost/model/scenario/result/ResponseBranch.java, core/src/main/java/com/apighost/model/scenario/result/ScenarioResult.java, core/src/main/java/com/apighost/model/scenario/result/StepResult.java, core/src/main/java/com/apighost/model/scenario/result/ThenAction.java, core/src/main/java/com/apighost/model/scenario/result/WhenCondition.java
Create ScenarioResult with Getter and Builder
- #2
- Create ScenarioResult class with Builder and Getter
- Create StepResult, ResponseBranch, WhenCondition, and ThenAction classes with builder pattern
- Improve documentation with JavaDoc for each model
- Successfully compiled and build
- Verified builder and getter methods for all model classes
``` JSON
{
"scenarioId" : "SC-001",
"name" : "Signup Scenario",
"description" : "Validate new user registration and login process",
"executedAt" : "2025-04-23T14:15:00.000",
"totalDurationMs" : 550,
"averageDurationMs" : 275,
"filePath" : "/local/result/user",
"baseUrl" : "http://localhost:8080",
"results" : [ {
"stepName" : "signup",
"type" : "HTTP",
"method" : "POST",
"url" : "http://localhost:8080/api/signup",
"requestHeader" : {
"Authorization" …
```
=> feat(core): Create scenario result domain model

parser/build.gradle, parser/src/main/java/com/apighost/parser/scenario/writer/JsonScenarioResultWriter.java, parser/src/main/java/com/apighost/parser/scenario/writer/ScenarioResultWriter.java, parser/src/test/java/parser/scenario/writer/JsonScenarioResultWriterTest.java
- #2
- Create ScenarioResultWriter interface
- Create JsonScenarioResultWriter (implement ScenarioResultWriter)
- Create JsonScenarioResultWriterTest class (Junit)
Junit test
```
> Task :core:compileJava UP-TO-DATE
> Task :core:processResources UP-TO-DATE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :parser:compileJava UP-TO-DATE
> Task :parser:processResources UP-TO-DATE
> Task :parser:classes UP-TO-DATE
> Task :parser:compileTestJava UP-TO-DATE
> Task :parser:processTestResources UP-TO-DATE
> Task :parser:testClasses UP-TO-DATE
> Task :parser:test
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or …
```
=> feat(parser): scenario parser model to json

core/src/main/java/com/apighost/model/scenario/test/Expected.java, core/src/main/java/com/apighost/model/scenario/test/FormData.java, core/src/main/java/com/apighost/model/scenario/test/Position.java, core/src/main/java/com/apighost/model/scenario/test/Request.java, core/src/main/java/com/apighost/model/scenario/test/RequestBody.java, core/src/main/java/com/apighost/model/scenario/test/Route.java, core/src/main/java/com/apighost/model/scenario/test/Scenario.java, core/src/main/java/com/apighost/model/scenario/test/Step.java, core/src/main/java/com/apighost/model/scenario/test/Then.java
- [[Feature] Add YAML scenario parser #1](https://github.com/api-ghost/api-ghost/issues/1)
- I revised the DTOs based on the updated YAML file format.
- I will later refactor overlapping properties to be managed with Enums. However, since using Enums with Jackson currently causes issues related to the Builder pattern, this has been postponed.
- The status property has been changed from Object to String.
- JUnit test results confirmed that the DTOs are correctly converted.
- before transform
```yaml
name: string
description: string
timeoutMs: 1000
store:
key: value 
steps:
stepName:
type: string  
position:    
x: 100
y: 200
request:      
method: string  
url: string  
header:
headerName: value 
destination: string 
subscription: string
message: string    
action: string     
body: …
```
=> feat(core): Create scenario YAML model

core/build.gradle, core/src/main/java/com/apighost/model/scenario/result/ResponseBranch.java, core/src/main/java/com/apighost/model/scenario/result/ScenarioResult.java, core/src/main/java/com/apighost/model/scenario/result/StepResult.java, core/src/main/java/com/apighost/model/scenario/result/ThenAction.java, core/src/main/java/com/apighost/model/scenario/result/WhenCondition.java, parser/src/main/java/com/apighost/parser/scenario/reader/JsonScenarioResultReader.java, parser/src/main/java/com/apighost/parser/scenario/reader/ScenarioResultReader.java, parser/src/test/java/parser/scenario/writer/JsonScenarioResultReaderTest.java
- #2 
- Create ScenarioResultReader interface
- Create JsonScenarioResultReader (implement ScenarioResultReader)
- Create JsonScenarioResultReaderTest class (Junit)
Junit test
```
> Task :core:compileJava UP-TO-DATE
> Task :core:processResources UP-TO-DATE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :parser:compileJava UP-TO-DATE
> Task :parser:processResources UP-TO-DATE
> Task :parser:classes UP-TO-DATE
> Task :parser:compileTestJava
> Task :parser:processTestResources UP-TO-DATE
> Task :parser:testClasses
> Task :parser:test
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on …
```
=> feat(parser): scenario parser json to model

parser/src/test/java/parser/scenario/reader/JsonScenarioResultReaderTest.java
- #2 
- Fixed incorrect package path.
=> chore: Change JsonScenarioResultReaderTest package path

build.gradle, core/build.gradle, model/src/main/java/com/apighost/model/scenario/Scenario.java, parser/build.gradle, parser/src/main/java/com/apighost/parser/scenario/reader/ScenarioReader.java, parser/src/main/java/com/apighost/parser/scenario/reader/YamlScenarioReader.java, parser/src/main/java/com/apighost/parser/scenario/writer/ScenarioWriter.java, parser/src/main/java/com/apighost/parser/scenario/writer/YamlScenarioWriter.java, parser/src/test/java/parser/scenario/reader/YamlScenarioReaderTest.java, parser/src/test/java/parser/scenario/writer/YamlScenarioWriterTest.java
- [[Feature] Add YAML scenario parser #1](https://github.com/api-ghost/api-ghost/issues/1)
- I implemented logic to convert the received scenario DTO into a YAML file and save it to a specific local path.
- Conversely, I also implemented a reader function that converts a YAML file back into a Scenario DTO.
- (yaml writer) I created two versions of the DTO for testing: one with formData filled and JSON set to null, and another with JSON filled and formData set to null, to verify that the YAML file is generated correctly.
- (yaml writer) The attached code is the version where formData is populated, as a representative example.
- before dto
```java
static Scenario createMockJsonScenario() {
Map<String, Object> store = new HashMap<>();
store.put("key", "value");
Position position = new …
```
=> feat(core): Create scenario YAML reader, writer parser

model/src/main/java/com/apighost/model/scenario/result/ResultStep.java, parser/src/test/java/parser/scenario/reader/JsonScenarioResultReaderTest.java, parser/src/test/java/parser/scenario/writer/JsonScenarioResultWriterTest.java
- #2 
- Add nextStep 
- Change durationMs int to long
- Change builder requestSuccess to isRequestSuccess
- Update test to match model changes
Execute JUnit tests
=> chore: change scenario result model

core/build.gradle, core/src/main/java/com/apighost/scenario/validator/ScenarioValidator.java
Validator for pre-execution validation of scenario tests
- #10 
- Validator for pre-execution validation of scenario tests
=> feat: Create ScenarioValidator

core/build.gradle, core/src/main/java/com/apighost/validator/ScenarioValidator.java, core/src/test/java/core/validator/ScenarioValidatorTest.java, parser/src/main/java/com/apighost/parser/template/TemplateConvertor.java
- #10 
- Add parser, model module depedency to core module
- Change validator package
- Change ScenarioValidator conditions
- Create TemplateConvertor
- It change ${variable} to actual variable value
=> feat(parser): Create TemplateConvertor

model/src/main/java/com/apighost/model/scenario/ScenarioResult.java
- Please specify the issue number linked to this PR. (e.g., Fixes #<issue_number>)
- Provide a clear and concise summary of what this PR includes.
- List the key changes introduced in bullet points.
- Describe how the changes were tested.
- Include test results, logs, or screenshots if necessary.
- Add any context or reference information that may help reviewers understand the changes.
=> fix: Fix isScenarioSucess getter

cli/src/main/java/com/apighost/cli/command/ViewResultCommand.java
- change getter
- Describe how the changes were tested.
- Include test results, logs, or screenshots if necessary.
- Add any context or reference information that may help reviewers understand the changes.
=>  hotfix: Change getter

core/src/main/java/com/apighost/scenario/callback/ScenarioResultCallback.java, core/src/main/java/com/apighost/scenario/executor/HTTPStepExecutor.java, core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java, core/src/main/java/com/apighost/scenario/executor/StepExecutor.java, core/src/test/java/core/scenario/HTTPStepExecutorTest.java, core/src/test/java/core/scenario/ScenarioTestExecutorTest.java
- #10
- Create execution engine for scenario-based testing, including both core execution logic and initial HTTP support.
- Implemented ScenarioTestExecutor to run sequential test scenarios with branching logic and timeout tracking.
- Implemented HTTPStepExecutor to support HTTP step execution with JSON body flattening and header handling.
- Integrated route matching logic based on expected status codes and response values.
- Added support for ScenarioResultCallback with default no-op methods.
-  Manually tested using https://httpbin.org/status/200 as a real HTTP endpoint
- Verified route transitions and success flag propagation across steps
- Unit tests:
- ScenarioTestExecutorTest.testExecute_successScenario_returnsValidResult
- …
=> feat(core): scenario test executor

cli/build.gradle, cli/src/main/java/com/apighost/cli/command/FileType.java, cli/src/main/java/com/apighost/cli/command/ViewResultCommand.java, cli/src/main/java/com/apighost/cli/command/ViewResultListCommand.java, cli/src/main/java/com/apighost/cli/command/ViewScenarioCommand.java, cli/src/main/java/com/apighost/cli/command/ViewScenarioListCommand.java, cli/src/main/java/com/apighost/cli/server/JettyServer.java, cli/src/main/java/com/apighost/cli/util/FileUtil.java, settings.gradle, web/build.gradle, web/src/main/java/com/apighost/web/controller/ApiController.java, web/src/main/java/com/apighost/web/controller/EndpointJsonController.java, web/src/main/java/com/apighost/web/controller/ResultInfoController.java, web/src/main/java/com/apighost/web/controller/ResultListController.java, web/src/main/java/com/apighost/web/controller/ScenarioInfoController.java, web/src/main/java/com/apighost/web/controller/ScenarioListController.java, web/src/main/java/com/apighost/web/controller/ScenarioTestController.java, web/src/main/java/com/apighost/web/filter/CorsFilter.java, web/src/main/java/com/apighost/web/sevlet/ApiFrontControllerServlet.java, web/src/main/java/com/apighost/web/util/FileType.java, web/src/main/java/com/apighost/web/util/FileUtil.java, web/src/main/java/com/apighost/web/util/JsonUtils.java
- [[Feature] Implemented Servlets for GUI Integration #21](https://github.com/api-ghost/api-ghost/issues/21)
This pull request includes the overall structure of a basic vanilla servlet project that handles responses when the Tool sends requests, as well as the implementation of some servlets that handle specific APIs.
<br>
- A filter for registering CORS settings with Jetty
- Implementation of `ApiFrontController.java`, which acts as the DispatcherServlet in Spring Boot
- Additional Jetty configuration
- Gradle dependency updates
- Implementation of utility classes to be used in vanilla servlet logic
- Implementation of the `/apighost/scenario-list` API based on the API specification
- Implementation of the `/apighost/result-list` API based on the API specification
- Implementation of the …
=> feat(web): servlet connect with gui

model/src/main/java/com/apighost/model/scenario/result/ResultStep.java
=> hotfix: Fix wrong getter

core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java, core/src/test/java/core/scenario/HTTPStepExecutorTest.java, core/src/test/java/core/scenario/ScenarioTestExecutorTest.java
- Apply changed isRequestSuccess getter
=> hotfix: Apply changed isRequestSuccess getter

cli/src/main/java/com/apighost/cli/ApiGhostCli.java, cli/src/main/java/com/apighost/cli/callback/CliScenarioResultCallback.java, cli/src/main/java/com/apighost/cli/command/ExecuteScenairoCommand.java, cli/src/main/java/com/apighost/cli/util/ConsoleOutput.java, cli/src/main/java/com/apighost/cli/util/FileUtil.java, core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java, core/src/test/java/core/scenario/ScenarioTestExecutorTest.java
- #13 
- Create CLI execute scenario test command
- Read scenario test file and execute scenario test
- Write scenario test result 
- Tested on CLI
- Execute 
``` bash
./gradlew :cli:run --args="apighost executor scenario-test.yaml"   
```
=> feat(cli): Create cli execute scenario command

settings.gradle, util/build.gradle, util/src/main/java/com/apighost/util/file/FileType.java, util/src/main/java/com/apighost/util/file/FileUtil.java, web/build.gradle
Move FileType and FileUtil to util module
- Move FileUtil and FileType to util module
=> reafactor(util): Create util module

generator/build.gradle, generator/src/main/java/com/apighost/generate/StructuredDataGenerator.java, generator/src/main/java/com/apighost/loader/PropertyLoader.java, generator/src/main/java/com/apighost/model/GeneratedData.java, generator/src/main/java/com/apighost/model/ObjectMapperHolder.java, generator/src/main/java/com/apighost/openai/FieldMetaPromptBuilder.java, generator/src/main/java/com/apighost/openai/OpenAiStructuredDataGenerator.java, generator/src/main/java/com/apighost/orchestrator/DataGenerationOrchestrator.java, generator/src/main/java/com/apighost/orchestrator/OpenAiGenerateOrchestrator.java, generator/src/main/java/com/apighost/parser/OpenAiResponseParser.java, model/src/main/java/com/apighost/model/collector/FieldMeta.java, settings.gradle
- #33 
- Added and developed the Generator module.
- Implemented with a focus on scalability and maintainability.
- Added functionality to generate request bodies and parameters using OpenAI.
```json
[
{
"type": "String",
"name": "name",
"nestedFields": []
},
{
"type": "String",
"name": "email",
"nestedFields": []
},
{
"type": "int",
"name": "password",
"nestedFields": []
},
{
"type": "JoinUserRequest",
"name": "joinUserRequest",
"nestedFields": [
{
"type": "String",
"name": "name",
"nestedFields": []
},
{
"type": "String",
"name": "email",
"nestedFields": []
},
{
"type": "String",
"name": "password",
"nestedFields": []
},
{
"type": "boolean",
"name": "isSuccess",
"nestedFields": []
}
]
}
]
```
```json
[
{
"name": "name",
"value": "John Doe"
},
{
"name": "email",
"value": …
```
=> feat(generator): Implement Generator

.gitignore, generator/.gitignore, generator/src/main/resources/openai.properties, gradle/wrapper/gradle-wrapper.properties
- Add gradle-wrapper.properties
- Add openai.properties
- Add gitignore
=> chore: add resources

util/src/main/java/com/apighost/util/file/ExecutionTimer.java
-
- Added a utility function to measure the execution time of a method.
- Utilized the functional interface Supplier for functional-style programming.
```java
ExecutionTimer.DurationResult<ResponseEntity<String>> response = ExecutionTimer.execute(
() ->
restTemplate.exchange(request.getUrl(), httpMethod, httpEntity,
String.class)
);
```
- Captures the start time, end time, duration, and result of an HTTP request.
=> feat(util): Implement ExecutionTimer using supplier

cli/src/main/java/com/apighost/cli/command/ShowGuiCommand.java, cli/src/main/java/com/apighost/cli/server/JettyServer.java, parser/src/main/java/com/apighost/parser/scenario/reader/YamlScenarioReader.java, web/src/main/java/com/apighost/web/controller/ResultInfoController.java, web/src/main/java/com/apighost/web/controller/ResultListController.java, web/src/main/java/com/apighost/web/controller/ScenarioInfoController.java
- [[Feature] Implemented Servlets for GUI Integration #21](https://github.com/api-ghost/api-ghost/issues/21)
- This pull request includes some changes that occurred while integrating the index.html build output of apighost ui, which was provided on May 9.
- List the key changes introduced in bullet points.
- As of now, based on the API specification documented in Notion, the following three endpoints have been successfully connected:
`GET /apighost/scenario-list`
`GET /apighost/result-list`
`GET /apighost/result-info`
- the Jetty server was launched directly to verify that the tests run correctly.
=> fix(web) : gui connect fix

model/src/main/java/com/apighost/model/loadtest/result/LoadTestSummary.java
- #47 
- I fixed a bug that was caused by importing Endpoint from an incorrect location.
=> hotfix(model): import code of endpoint fixed

loadtest/build.gradle, loadtest/src/main/java/com/apighost/loadtest/publisher/CompositeResultPublisher.java, loadtest/src/main/java/com/apighost/loadtest/publisher/ResultPublisher.java, settings.gradle
- #42 
- Create loadtest module 
- Create ReusltPublisher interface for publish load test results
- Create CompositeResultPublisher to support multiple publisher
- To use this with the load test, implement this interface and inject it accordingly.
=> feat: Create load test result publisher

model/src/main/java/com/apighost/model/loadtest/parameter/LoadTestExecuteParameter.java, model/src/main/java/com/apighost/model/loadtest/parameter/Stage.java, model/src/main/java/com/apighost/model/loadtest/result/Result.java, parser/build.gradle, parser/src/main/java/com/apighost/parser/loadtest/converter/LoadTestParameterConverter.java, parser/src/test/java/loadtest/writer/YamlLoadTestParameterWriterTest.java, util/src/main/java/com/apighost/util/file/BasePathHolder.java
#39 
- This PR contains the logic that converts the scenario name in a YAML file into an actual Scenario object within the load test executor.
- The converter takes a LoadTestParameter as a parameter and transforms it into a LoadTestExecuteParameter.
- The test code is currently under development, but it's proving to be challenging. I plan to thoroughly improve and supplement it later.
=> Feat(parser):  create loadtest-executer-param model and converter

core/src/main/java/com/apighost/scenario/executor/WebSocketManager.java, core/src/main/java/com/apighost/scenario/executor/WebSocketStepExecutor.java, core/src/main/java/com/apighost/util/ExecutionTimer.java, core/src/main/java/com/apighost/util/TimeUtils.java, model/src/main/java/com/apighost/model/scenario/WebSocketStatusCode.java, model/src/main/java/com/apighost/model/scenario/step/HTTPMethod.java, parser/src/test/java/parser/scenario/reader/JsonScenarioResultReaderTest.java
- #53 
- Designed to support WebSocket testing in scenario-based and load testing environments.
- Implemented with concurrency considerations for multi-threaded environments.
<p align="center">
</p>
- Socket connection success!
<p align="center">
</p>
=> feat(core): Implement websocket executor

model/src/main/java/com/apighost/model/collector/Endpoint.java
=> hotfix(model): change-endpoint-model

cli/build.gradle, cli/src/main/java/com/apighost/cli/ApiGhostCli.java, cli/src/main/java/com/apighost/cli/command/ViewLoadTestParamCommand.java, cli/src/main/java/com/apighost/cli/command/ViewLoadTestParamListCommand.java, cli/src/main/java/com/apighost/cli/command/ViewScenarioListCommand.java, cli/src/main/java/com/apighost/cli/util/CliUtil.java, util/src/main/java/com/apighost/util/file/FileType.java
#44 
- This PR includes implementations related to the CLI commands for Loadtest.
- The build.gradle file, CliUtil, and FileType have been modified or added to support the Loadtest commands.
- You can use the following commands to edit or read YAML files related to Loadtest parameters.
`apighost edit-load fileName.yaml` <br> 
`apighost edit-load --create fileName.yaml` <br>
`apighost edit-load -c fileName.yaml`
- In addition, the following command allows you to retrieve a list of available Loadtest parameter files.<br>
`apighost ls loadtest` 
<br>
=> feat(cli): loadtest command

core/src/main/java/com/apighost/scenario/executor/HTTPStepExecutor.java, core/src/main/java/com/apighost/validator/ScenarioValidator.java
- Change scenario when routes is null or empty
Verify Junit test
=> hotfix(core): Change scenario when routes is null or empty

web/build.gradle, web/src/main/java/com/apighost/web/controller/LoadTestExportController.java, web/src/main/java/com/apighost/web/controller/LoadTestInfoController.java, web/src/main/java/com/apighost/web/controller/LoadTestListController.java, web/src/main/java/com/apighost/web/filter/CorsFilter.java, web/src/main/java/com/apighost/web/servlet/ApiFrontControllerServlet.java
- #59 
- GET `/apighost/loadtest-list`: Retrieve a list of load test configuration files
- POST `/apighost/loadtest-export`: Create a new load test configuration file
- GET `/apighost/loadtest-info`: View detailed information of a load test configuration file
- I will write the test code later to thoroughly verify the implementation.
- The API for executing the load test and checking the SSE is not yet complete.
=> feat(web): create loadtest servlet

model/src/main/java/com/apighost/model/loadtest/parameter/LoadTestExecuteParameter.java, model/src/main/java/com/apighost/model/loadtest/parameter/LoadTestParameter.java, parser/src/test/java/parser/loadtest/reader/YamlLoadTestParameterReaderTest.java, parser/src/test/java/parser/loadtest/writer/YamlLoadTestParameterWriterTest.java
- #39 
- #55 
- Change thinkTimeMs long to Long (nullable)
- Applied model changes to tests.
Verify Junit test.
=> refactor(model): Change load test model

cli/build.gradle, cli/src/main/java/com/apighost/cli/publisher/BufferedCliPublisher.java, cli/src/main/java/com/apighost/cli/util/console/AnsiEscapeUtil.java, cli/src/main/java/com/apighost/cli/util/console/DynamicDisplayManager.java, cli/src/main/java/com/apighost/cli/util/console/LoadTestReporter.java
- #57 
- Using the ANSI escape syntax, the output is updated in place rather than appended below the existing content. This allows the current content to be refreshed dynamically instead of printing new lines each time.
- For now, the output simply displays the results in a basic format. Enhancements such as color styling and better formatting will be applied later.
- For now, only the part that is transmitted every 5 seconds is displayed. I will implement the final summary event output later.
=> feat(cli): create ANSI escape logic

cli/src/main/java/com/apighost/cli/ApiGhostCli.java, cli/src/main/java/com/apighost/cli/command/DeleteLoadTestParameterCommand.java
- #44 
- This PR includes the definition of a command to delete scenario test files or load test configuration files.
- When you enter apighost rm fileName, the file matching fileName will be deleted from the `.apighost/SCENARIO` and `.apighost/LOADTEST` folders inside the user directory.
- 
-
=> feat(cli): create file delete command

loadtest/src/main/java/com/apighost/loadtest/parameter/StageExecuteParameter.java, loadtest/src/main/java/com/apighost/loadtest/parameter/StageExecuteParameterResolver.java, loadtest/src/main/java/com/apighost/loadtest/validator/LoadTestValidator.java
- #42
- Add StageExecuteParameter model to represent configuration for each load test stage.
- Implement StageExecuteParameterResolver to fill in default values for nullable fields.
- Implement validator for validate parameter
=> feat(loadtest): Create load test parameter

loadtest/src/main/java/com/apighost/loadtest/metrics/LoadTestSnapshotAggregator.java, loadtest/src/main/java/com/apighost/loadtest/metrics/MetricCalculator.java, loadtest/src/main/java/com/apighost/loadtest/metrics/ResultBuffer.java, util/src/main/java/com/apighost/util/file/TimeUtils.java
- #42 
- Manage load test result data
- Calculate metrics data
=> feat(loadtest): Create load test metrics managing

loadtest/src/main/java/com/apighost/loadtest/lifecycle/VuLifecycleManager.java, loadtest/src/main/java/com/apighost/loadtest/scheduler/ResultScheduler.java
- #42 
- Manage addition, cancellation, and status of executing virtual users. 
- Schedule periodic publishing using Java ScheduledExecutorService.
=> feat(loadtest): Create load test scheduler

loadtest/build.gradle, loadtest/src/main/java/com/apighost/loadtest/LoadTestOrchestrator.java, loadtest/src/main/java/com/apighost/loadtest/executor/LoadTestExecutor.java, loadtest/src/main/java/com/apighost/loadtest/executor/RampUpStageExecutor.java, loadtest/src/main/java/com/apighost/loadtest/executor/StageExecutor.java
- #42 
- Create loadtest executor
- Create loadtest orchestrator
- Use Orchestrator
=> feat(loadtest): create load test executor

loadtest/src/main/java/com/apighost/loadtest/metrics/ResultBuffer.java
=> hotfix(loadtest): ResultBuffer null check

core/src/main/java/com/apighost/scenario/executor/ScenarioTestExecutor.java
- Handle the case where the callback is null by providing a default behavior.
Verify Junit tests
=> hotfix(core): Add scenario execution if callback is null

web/src/main/java/com/apighost/web/controller/ResultInfoController.java, web/src/main/java/com/apighost/web/controller/ScenarioExportController.java, web/src/main/java/com/apighost/web/controller/ScenarioInfoController.java, web/src/main/java/com/apighost/web/controller/ScenarioTestController.java, web/src/main/java/com/apighost/web/util/FileUtil.java
- Please specify the issue number linked to this PR. (e.g., Fixes #<issue_number>)
- Modified the responses to align with the updated API specifications.
- Fixed an issue where a prefix was incorrectly added when saving scenario files.
- Updated the file name format used when saving result files.
-
=> fix(web): bugs about responses

cli/src/main/java/com/apighost/cli/command/ExecuteScenairoCommand.java, cli/src/main/java/com/apighost/cli/publisher/BufferedCliPublisher.java, cli/src/main/java/com/apighost/cli/util/console/AnsiEscapeUtil.java, cli/src/main/java/com/apighost/cli/util/console/DynamicDisplayManager.java, cli/src/main/java/com/apighost/cli/util/console/LoadTestReporter.java
- Please specify the issue number linked to this PR. (e.g., Fixes #<issue_number>)
- This PR enables real-time dynamic display of load test results in the CLI console every 5 seconds during execution.
- It resolves a previous issue where each new line was pushed down, preventing proper result updates.
- Various ANSI escape codes were utilized to solve the problem.
- Verified that real-time results are displayed correctly by running the project with gradlew run.
=> fix(cli): dynamic load test result output

cli/src/main/resources/logback.xml, web/build.gradle, web/src/main/java/com/apighost/web/controller/FileRemoveController.java, web/src/main/java/com/apighost/web/controller/GenerateDataController.java, web/src/main/java/com/apighost/web/controller/ScenarioExportController.java, web/src/main/java/com/apighost/web/servlet/ApiFrontControllerServlet.java, web/src/main/java/com/apighost/web/util/JsonUtils.java, web/src/main/java/com/apighost/web/util/OpenAIKeyHolder.java
- #33 
-This PR includes a controller for deleting files and a controller that utilizes the OpenAI API to automatically fill in the field values of a request body.
- Sensitive information such as the OpenAI key is retrieved from the .apighost/api-ghost.yaml file, where users input their own keys. Therefore, a class named OpenAIKeyHolder was created to parse this YAML file and fetch the key.
- Testing was done using Postman and by directly running the GUI.
-
=> feat(web): scenario delete login and LLM

core/build.gradle, core/src/test/java/core/scenario/HTTPStepExecutorTest.java, core/src/test/java/core/scenario/ScenarioTestExecutorTest.java
- Replaced actual HTTP requests with MockWebServer requests.
- Improved test stability to ensure consistent execution across environments.
Verify Junit test
-  Add test conditions later.
=> fix(core): scenario test to mock web server

cli/src/main/java/com/apighost/cli/util/console/AnsiEscapeUtil.java, cli/src/main/java/com/apighost/cli/util/console/LoadTestReporter.java
- Fixed output issue in Linux (Ubuntu) environment.
Test in linux ubuntu environment.
=> hotfix(cli): Fix when write on linux error

web/src/main/java/com/apighost/web/servlet/StaticResourceServlet.java
- 
- Fixed the issue where refreshing a page under apighost-ui/ would result in a 404 error.
- I started it up using the Jetty server.
=> fix(cli): added redirect error logic

LICENSE, README.md
- #87 
- update readme file
- add MIT License
- This README places QuickStart at the beginning so that first-time users can easily read it and see meaningful results within 5 minutes, while also defining what APIs are implemented and what commands are available.
- I also made an effort to include the relationships with other modules.
=> docs(readme): Update README.md
